name: Deploy Backend to Azure Functions

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: |
        cd backend/TaskApp.Functions
        dotnet restore

    - name: Build project
      run: |
        cd backend/TaskApp.Functions
        dotnet build --configuration Release --no-restore

    - name: Publish project
      run: |
        cd backend/TaskApp.Functions
        dotnet publish --configuration Release --no-build --output ./output

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'func-taskapp-72728'
        slot-name: 'production'
        package: './backend/TaskApp.Functions/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Configure App Settings
      run: |
        az functionapp config appsettings set \
          --name func-taskapp-72728 \
          --resource-group rg-taskapp-portfolio \
          --settings "SqlConnectionString=${{ secrets.SQL_CONNECTION_STRING }}"
